version: 1
services:
  - type: web
    name: flare-server
    env: node
    buildCommand: cd server && pnpm install
    startCommand: cd server && pnpm start
    healthCheckPath: /
    autoDeploy: true
    branch: main
